version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html

hooks:
  AfterInstall:
    - location: install_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_nginx.sh
      timeout: 300
      runas: root
