version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: install_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_nginx.sh
      timeout: 300
      runas: root
